wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1648382520
    t:
      1:
      - 12
      - 45
      2:
      - 12
      - 45
      3:
      - 17
      4: 3.7.13
      5: 0.12.11
      8:
      - 5
      10:
      - 3
